server.port: 8090
spring:
  jpa:
    hibernate.ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/secondhandOnlineshop
    username: secondhand
    password: secondhand